name: Deploy website to FTP
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Sync files with FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.GH_DEPLOY_FTP_SERVER }}
          username: ${{ secrets.GH_DEPLOY_FTP_USERNAME }}
          password: ${{ secrets.GH_DEPLOY_FTP_PASSWORD }}
          port: 21
          local-dir: ./
